repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files # Check for large files added to Git
      # - id: check-toml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
  - hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
